### PR TITLE
kanagawa themes

### PR DESCRIPTION
**Pull request by leviszaboo**
Hey,

I added some new colors for the lotus theme and a function that sets the theme based on the @kanagawa-theme tmux options. Maybe the exact color combinations could be tweaked a little but I found that overall they match the general themes well. It still uses the base color variable names from the dracula repo, maybe that's something to work on later.

Lotus theme:
Screenshot 2024-05-20 at 17 28 06

Default theme:
Screenshot 2024-05-20 at 17 27 47

Dragon theme:
Screenshot 2024-05-20 at 17 27 31

### CODE REVIEW

**Comment by Nybkox** [comment]
lgtm

**Comment by sabattle** [comment]
@leviszaboo just tried these changes and my status bar colors when using the `dragon` theme don't look anything like yours in the provided example screenshot. are you doing some additional customization in those images?

**Comment by leviszaboo** [comment]
@sabattle this is my .tmux.conf, I commented out my specific color configuration so that only the theme is set. How does it look on yours?

Screenshot 2024-05-20 at 23 50 00

**Comment by Nybkox** [comment]
For me, dragon looks like that.
image

**Comment by sabattle** [comment]
Here's the relevant portion of the tmux.conf, basically just copied all of the enabled settings I saw in your screenshot:
```
# Theme
set -g @plugin 'Nybkox/tmux-kanagawa'
set -g @kanagawa-border-contrast true
set -g @kanagawa-show-powerline true

set -g @kanagawa-plugins "battery cpu-usage ram-usage time"
set -g @kanagawa-theme "dragon"
set -g @kanagawa-left-icon-padding-right 3
set -g @kanagawa-left-icon-padding-left 2
set -g @kanagawa-left-icon-margin-right 0
set -g status-justify left
```
And here's what the status bar looks like in my current terminal (alacritty, with dragon theming)

Screenshot 2024-05-20 at 7 30 02 PM

Biggest things that stand out to me are that your grays are completely different. Maybe this is just an issue of `TERM` color settings, though? I have True Color enabled, and tmux is set to `tmux-256color`.

**Comment by Nybkox** [comment]
@sabattle, the status bar looks the same as in my screenshot. The theme does not set window-style / window-active-style, so the background is different because my color is taken from the emulator settings.
https://github.com/Nybkox/tmux-kanagawa/issues/4

**Comment by sabattle** [comment]
sorry, I was actually responding to @leviszaboo in reference to my comment about color differences. @Nybkox, our status bars do look the same, yeah, but they both look different than his `dragon` theme.

**Comment by leviszaboo** [comment]
@sabattle You were right. I've also noticed a couple months ago that the colors in my tmux status bar are rendered a bit differently but I honestly forgot it at this point. But for example: 

Screenshot 2024-05-21 at 09 11 57

After checking out [this issue](https://github.com/alacritty/alacritty/issues/3354) I added a terminal-overrides line to force a terminal with true-color capabilities. And now my dragon theme looks like yours:

Screenshot 2024-05-21 at 09 29 02

Although with this in mind the dragon theme could be reworked a little, because the light-gray/light-purple color does not really match it imo and I honestly like the one that I had before a bit more. Thanks for pointing it out, though.

**Comment by leviszaboo** [comment]
I updated the themes in a new pull request. This is how the dragon looks now with my settings:
Screenshot 2024-05-21 at 12 38 15

**Comment by sabattle** [comment]
@leviszaboo no worries, glad you figured it out! yea the whole reason I even said anything was because I preferred how the theming looked in your original screenshot. appreciate the new themes

**Pull request merged**
